### ISSUE TITLE
Rust implimentation nitpick

### ISSUE THREAD

**Issue by EtomicBomb** [superwhiskers/question#22]
Hello, this repository looks like a really good resource and I'm happy something like it exists. I saw the Rust example on Wikipedia, and I don't think it fairly represents idiomatic Rust code. I am certainly no Rust expert though.

* Usage of the option type. It feels unnecessary. I think it's great that you want to showcase this type, but I question whether it fits here. It seems like most of the other implementations don't have any similar behaviour. Reading the function signature, it's not obvious what a `None` value should represent (Are there no valid responses?). Possibly the intent might be more clear with a custom enum? Honestly, my opinion is that you should just ditch the `Option` and make the function accept a `&[String]`

* Constantly checking whether `vaild.is_some()` or `.is_none()`. This kinda goes against the strength of Rust's enum/match pattern. Honestly, I feel like there are two different 'modes' to this function: the mode where any input is valid, and the mode where there are a list of valid inputs you're checking against. I think you should just ditch the any-input-is-valid mode (other examples in this project don't have it), but if you want to keep it I suggest wrapping all of the code in the function in a huge match.

* Declaring `input` at the top of the function. First I thought this was done to avoid re-allocating the String's memory, but then I saw the `input = "".to_string()` at the end of the loop. I think it's more clear to declare `let mut input = String::new()` right before you fill it with stdin.

* Using `String::pop` to remove the trailing newline. There's a function, `str::trim_end` that's intended for this. Also one `.pop()` might not work on platforms with two-character line endings. 
* Using a `for` loop to check if the input is valid. I think the `slice::contains` method would more clear here, it's certainly less code. 

* Error handling with `Result::expect`. All of the errors that are handled with expect seem very unlikely - it's not often that flushing stdout or reading from stdin will fail, so you probably don't have to do anything verbose.  I'm not sure what the alternative is, possibly you could return an `io::Result<String>` from this function and show off the fancy `?` operator?

* Returning a `&[&str]`. This nitpick will be more controversial than the other ones. Values of the type `&[&str]` are hard to construct unless you do it with a literal. For example, if you were reading the valid responses from a file into a Vec<String>, you would need a line like `vec_of_strings.iter().map(String::as_str).collect::<Vec<_>>()` to do the conversion. I'm not sure what the idiom is though. 

* Lack of comments. I think your code is readible enough, but something going on Wikipedia that's intended to be read by new Rustaceans probably needs clarification.

My suggestion: 
```rust
fn question(prompt: &str, valid: &[String]) -> io::Result<String> {
    // construct a string with the possible responses
    let joined_valid = valid.join(", ");

    loop {
        // display the prompt to the user
        print!("{}\n({}): ", prompt, joined_valid);
        io::stdout().flush()?;

        // get the input from the user, and remove trailing newlines
        let mut input = String::new();
        io::stdin().read_line(&mut input)?;
        input = input.trim_end().to_string(); 

        // if their response is valid, exit the loop and return
        if valid.contains(&input) {
            break Ok(input);
        }

        // uh oh, they chose an invalid response, let them know...
        println!("\"{}\" is not a valid answer", input);
        // and try again!
    }
}

fn main() -> io::Result<()> {
    let cheeses = ["cheddar".into(), "swiss".into()];
    let response = question("What's your favorite kind of cheese?", &cheeses)?;
    println!("I like {} too!", response);
    Ok(())
}
```
Obviously this code could be improved too (esp. the comments) but it's a step in the right direction

**Comment by EtomicBomb** [comment]
I just found that someone made a pull request with another Rust implementation. I like that one. I still question the need for making valid `Option`al

**Comment by superwhiskers** [comment]
> Usage of the option type. It feels unnecessary. I think it's great that you want to showcase this type, but I question whether it fits here. It seems like most of the other implementations don't have any similar behaviour. Reading the function signature, it's not obvious what a `None` value should represent (Are there no valid responses?). Possibly the intent might be more clear with a custom enum? Honestly, my opinion is that you should just ditch the `Option` and make the function accept a `&[String]`

this decision was done mainly as it made more "sense" to me when writing it, as simply having an empty slice passed can also signify that there are _no valid responses_, which sounds useless, but differentiation between having _no vallid responses_ and _only valid responses_ seemed necessary to me. the proposed implementation doesn't appear to handle cases where it accepts any input in addition to cases where there is a fixed set of valid inputs, which is really the only reason that the optional was there.

> Constantly checking whether `vaild.is_some()` or `.is_none()`. This kinda goes against the strength of Rust's enum/match pattern. Honestly, I feel like there are two different 'modes' to this function: the mode where any input is valid, and the mode where there are a list of valid inputs you're checking against. I think you should just ditch the any-input-is-valid mode (other examples in this project don't have it), but if you want to keep it I suggest wrapping all of the code in the function in a huge match.

each implementation in this project has the two modes of operation. let's take the simplest, the python one

```python
def question(prompt, valid):
        inp = ''
	while True:
	
		print(prompt)
		if len(valid) != 0:
			inp = input(f'({", ".join(valid)}): ')
		else:
			inp = input(': ')
		
		if len(valid) == 0:
			return inp
		
		for ele in valid:
			if ele == inp:
				return inp
		
		print(f'"{inp}" is not a valid answer')
```

where `if len(valid) != 0` and `if len(valid) == 0` are is where the check is done. the only real difference here is that it lacks an optional and instead uses the length of the list to determine whether to accept any input or to instead accept a subset of all valid inputs

as far as wrapping all of the code in a `match` statement goes, i wouldn't do that, as it would have needlessly duplicated code, which seems like it would only be more confusing

 > Declaring `input` at the top of the function. First I thought this was done to avoid re-allocating the String's memory, but then I saw the `input = "".to_string()` at the end of the loop. I think it's more clear to declare `let mut input = String::new()` right before you fill it with stdin.

this i do agree with, although i would instead use `input.clear()` and a comment instead of allocating right where the string is needed

> Using `String::pop` to remove the trailing newline. There's a function, `str::trim_end` that's intended for this. Also one `.pop()` might not work on platforms with two-character line endings.

this is largely fine. the only issue is that simply calling `str::trim_end` and turning that into a `String` is that it allocates even more memory. this could be reduced by passing around the slice and only turning it into a `String` when it is returned from the function

> Using a `for` loop to check if the input is valid. I think the `slice::contains` method would more clear here, it's certainly less code.

this is also a welcome change. i have no issues with this

> Error handling with `Result::expect`. All of the errors that are handled with expect seem very unlikely - it's not often that flushing stdout or reading from stdin will fail, so you probably don't have to do anything verbose. I'm not sure what the alternative is, possibly you could return an `io::Result<String>` from this function and show off the fancy `?` operator?

this was only used to provide _a message_ instead of simply calling `unwrap`, which i see as being bad practice. returning an `io::Result<String>` also works, though

> Returning a `&[&str]`. This nitpick will be more controversial than the other ones. Values of the type `&[&str]` are hard to construct unless you do it with a literal. For example, if you were reading the valid responses from a file into a Vec, you would need a line like `vec_of_strings.iter().map(String::as_str).collect::<Vec<_>>()` to do the conversion. I'm not sure what the idiom is though.

this is no longer done, but i also see a `Cow<'a, str>` working, however, that would be more complicated to work with given lifetimes and such

> Lack of comments. I think your code is readible enough, but something going on Wikipedia that's intended to be read by new Rustaceans probably needs clarification.

this is fine

i now propose this version, instead

```rust
use std::io::{self, stdout, stdin, Write};

fn question(prompt: &str, valid: Option<&[&str]>) -> io::Result<String> {
    // declare both the input buffer as well as the string listing the possible responses
    // beforehand to avoid allocating memory
    let joined_valid = valid.map(|v| v.join(", "));
    let mut input = String::new();

    loop {
        // output the prompt, displaying possible responses if necessary
        println!("{}", prompt);
        match &joined_valid {
            Some(joined_valid) => print!("({}): ", joined_valid),
            None => print!(": "),
        }

        // flush the output stream to ensure that the prompt is visible while we await input
        stdout().flush()?;
        stdin().read_line(&mut input)?;
        
        // trim any line ending from the string and save the resulting slice, not allocating any
        // new String as we may not need it
        let trimmed_input = input.trim_end();

        // check if we are accepting all input or if their response is one of the accepted ones
        if valid.map_or(true, |v| v.contains(&trimmed_input)) {
            break Ok(trimmed_input.to_string());
        }

        // otherwise, their response was invalid, so we let them know
        println!("\"{}\" is not a valid answer", trimmed_input);

        // clear the input buffer
        input.clear();

        // ...and loop around, trying again
    }
}

fn main() -> io::Result<()> {
    // we may use a better example here instead of a generic one
    question("foo", Some(&["bar", "baz"]))?;
    question("foo", None)?;
    Ok(())
}
```

**Comment by superwhiskers** [comment]
since there hasn't been discussion for two weeks now, i have pushed the proposed implementation and will now close this.
